command:
  - uvicorn
  - app.main:app
  - --host
  - 0.0.0.0
  - --port
  - 8000
env:
  - name: PGHOST
    valueFrom: resources.lakebase_db.host
  - name: PGPORT
    valueFrom: resources.lakebase_db.port
  - name: PGUSER
    valueFrom: resources.lakebase_db.user
  - name: PGPASSWORD
    valueFrom: resources.lakebase_db.password
  - name: PGDATABASE
    value: "postgres"
  - name: FMAPI_ENDPOINT
    value: "databricks-bge-small-en"
  - name: DELTA_CATALOG
    value: "appshield_catalog"
  - name: DELTA_SCHEMA
    value: "telemetry"
resources:
  - name: lakebase_db
    type: lakebase
